-- Migration: Create harvest_logs table for FSMA 204 Critical Tracking Events.
--
-- IMPORTANT: This table is DISTINCT from harvest_requests.
--   harvest_requests  = forward-looking supply signals posted by sellers for buyers to browse
--   harvest_logs      = actual past harvest events = FSMA 204 CTEs (Critical Tracking Events)
--
-- Every harvest_log gets an auto-generated Traceability Lot Code (TLC) at creation time.
-- Format: TLC-{ORG4}-{CROP4}-{YYYYMMDD}-{RAND4}   e.g. TLC-GREE-PLAN-20260315-X7K2
-- The lot code is the atomic unit of FSMA 204 traceability.

CREATE TABLE harvest_logs (
  id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  seller_org_id       UUID        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  plot_id             UUID        REFERENCES farm_plots(id) ON DELETE SET NULL,
  -- Crop identity
  crop                TEXT        NOT NULL,
  variety             TEXT,
  -- Actual harvest event data
  harvest_date        DATE        NOT NULL,
  quantity_harvested  NUMERIC(10, 3),
  unit                TEXT,               -- 'kg' | 'lb' | 'bunches' | 'cases' | 'bags' | etc.
  quality_notes       TEXT,
  -- Traceability Lot Code — generated by farm.service.ts at creation, never changes
  lot_code            TEXT        NOT NULL UNIQUE,
  -- Responsible party (FSMA 204 requires identifying who logged the harvest)
  responsible_party   UUID        REFERENCES users(id) ON DELETE SET NULL,
  -- Timestamps
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for the most common query patterns
CREATE INDEX idx_harvest_logs_seller_org_id  ON harvest_logs(seller_org_id);
CREATE INDEX idx_harvest_logs_lot_code       ON harvest_logs(lot_code);
CREATE INDEX idx_harvest_logs_harvest_date   ON harvest_logs(harvest_date DESC);
CREATE INDEX idx_harvest_logs_plot_id        ON harvest_logs(plot_id) WHERE plot_id IS NOT NULL;
CREATE INDEX idx_harvest_logs_crop           ON harvest_logs(seller_org_id, crop);

COMMENT ON TABLE  harvest_logs IS 'Actual harvest events = FSMA 204 Critical Tracking Events. Distinct from harvest_requests (supply forecasts).';
COMMENT ON COLUMN harvest_logs.lot_code IS 'Traceability Lot Code. Format: TLC-{ORG4}-{CROP4}-{YYYYMMDD}-{RAND4}. Auto-generated at creation. Never mutated.';
COMMENT ON COLUMN harvest_logs.unit IS 'Unit of measurement for quantity_harvested: kg, lb, bunches, cases, bags, etc.';

-- ─── Row-Level Security ───────────────────────────────────────────────────────

ALTER TABLE harvest_logs ENABLE ROW LEVEL SECURITY;

-- Sellers: full access to their own logs
CREATE POLICY harvest_logs_seller_own ON harvest_logs
  FOR ALL TO authenticated
  USING (
    seller_org_id IN (
      SELECT organization_id FROM organization_users WHERE user_id = auth.uid()
    )
  );

-- Admins: full access
CREATE POLICY harvest_logs_admin ON harvest_logs
  FOR ALL TO authenticated
  USING (
    EXISTS (SELECT 1 FROM users WHERE id = auth.uid() AND role IN ('admin', 'super_admin'))
  );

-- Public: read-only on lot_code lookups (for QR code verification — no auth required)
CREATE POLICY harvest_logs_public_read ON harvest_logs
  FOR SELECT TO anon, authenticated
  USING (true);
